### ISSUE TITLE
NPC Combat

### ISSUE THREAD

**Issue by MPNull** [nshusa/astraeus-legacy#26]
I pulled your latest updates from Git by "git pull" inside the project directories.

Noticed that the something has changed since clicking a Guard near Edgeville hits them (once) and combat ends. The monster that is being under attack doesn't attack back.

I'm aware about that the Combat System is under construction and doesn't work properly, but yesterday monsters were attacking back if being attacked by player.

**Comment by AlexMason** [comment]
`git pull` does not update from remote to master.  You should be using `git checkout`

**Comment by MPNull** [comment]
Anyways I got latest updates.

**Comment by Joshua-F** [comment]
@AlexMason `git pull` will pull changes from master if you're in the master branch, I'm not sure what  you're talking about.
